name: "typo"
description: "誤字/脱字修正テンプレート"
title: "[TYPO]"
labels:
  - "typo"
body:
  - type: textarea
    id: summary
    attributes:
      label: "修正箇所と修正案"
      placeholder: |
        一例
        ファイル名 ./README.md
        行列 20:7
        誤字 validaitons
        修正案 validations
    validations:
      required: true